source/antwerp/tier2_hardware.rst
source/antwerp/tier2_hardware/leibniz_hardware.rst
source/antwerp/uantwerp_SX_Aurara_TSUBASA.rst
source/antwerp/uantwerp_intel_toolchains.rst
source/antwerp/uantwerp_software_specifics.rst

I've made several changes to the UAntwerp-specific pages
- Linked to site-specific pages on our specific toolchain setup, licensed software and on the use of the visualisation node and the GPU nodes. We really need the latter two for our users.
- Also added information on the NEC SX Aurora node that was not previously available.

Changes to UAntwerp-specific pages

---

.gitignore
source/access/account_request.rst
source/access/generating_keys_with_openssh_on_os_x.rst
source/access/getting_access.rst
source/access/links.rst

We noticed that it is currently too hard to find relevant info on the account request procedure.  Specifically, the pages on generating SSH keys are well hidden, and require three click-throughs.
* Eliminate one level of redirection.
* Emphasize procedural links.
* Link to information that is on the VSC website, eliminate duplication.
Feel free to comment.

Restructured pages on getting access

---

source/access/getting_access.rst
source/faq.rst
source/software/links.rst
source/software/singularity.rst

* Add documentation on how to use Singularity on the VSC infrastructure.
The information on how to build images is intentionally brief: there is no point in reproducing Sylabs' documentation and risking that ours is outdated after a short while.
Question: do all sites support Singularity, and more specifcally, Singularity 3.x?  If not, let me know, and I'll move this documentation to the Leuven specific part.

Singularity documentation

---

source/access/data_transfer_using_winscp.rst
source/access/how_to_create_manage_vsc_groups.rst
source/access/setting_up_a_ssh_proxy.rst
source/access/text_mode_access_using_putty.rst
source/jobs/using_software.rst
source/leuven/thinking7_quickstart.rst
source/leuven/tier2_hardware/thinking_hardware.rst
source/software/intel_toolchain.rst

- remark: still issues with "lmod" in jobs/using_software.rst
(see jobs/links.rst and gent/setting_up_the_environment_using_lmod_at_the_hpc_ugent_clusters.rst)
and "open mpi" in software/mpi_for_distributed_programming.rst
(see software/links.rst and software/foss_toolchain.rst)

Fixed typos in (references to) labels

---

source/index.rst

Proposal to add FAQ reference to landing page.  Refers to open issue #52

Add FAQ page reference to landing page

---

source/access/where_can_i_store_what_kind_of_data.rst
source/jobs/vsc_variables.rst

- fixed typos
- added VSC_SCRATCH to list of scratch related variables mentioned under
storage options
- removed double entry VSC_SCRATCH_SITE from VSC variables
- added VSC_SCRATCH_GLOBAL to VSC variables to be consistent with the variables
mentioned under storage options

Fixed typos

---

source/leuven/tier2_hardware/genius_login_nodes.rst

Although users can login using SSH to the NX nodes (nx.hpc.kuleuven.be and nx-tier1.hpc.kuleuven.be) they shouldn't.  These nodes simply route the login using the NX client to the appropriate login nodes of either genius or breniac.

Add remark on terminal login to NX login hosts

---

source/access/account_management.rst
source/access/linux_client.rst
source/access/setting_up_a_ssh_proxy.rst
source/access/setting_up_a_ssh_proxy_with_putty.rst
source/access/text_mode_access_using_putty.rst
source/access/windows_client.rst

The pages on configuring PuTTY and (to a lesser degree) OpenSSH to use a proxy cause quite some confusion for novice users, resulting in helpdesk tickets.
The references to the pages on configuring PuTTY and OpenSSH to use proxies have been removed, although the pages themselves still exist.
Explicit warnings have been added to the pages that contain screenshots on what has to be modified for the specific user/cluster.
A remark on switching on agent forwarding when configuring PuTTY has been added.

Proxy page die, die, die

---

source/access/account_management.rst
source/access/linux_client.rst
source/access/setting_up_a_ssh_proxy.rst
source/access/setting_up_a_ssh_proxy_with_putty.rst
source/access/text_mode_access_using_putty.rst
source/access/windows_client.rst

The confusing reference to proxy configuration has been removed from the PuTTY and OpenSSH documentation page.
However, the proxy configuration page has not been removed.  If you require it, refer to it from the appropriate location, most likely in site-specific documentation.
This resolves issue #77

Remove reference to proxy configuration page

---

source/jobs/worker_framework.rst
source/jobs/worker_or_atools.rst
source/leuven/running_jupyter_notebooks.rst
source/leuven/tier2_hardware/superdome_hardware.rst
source/leuven/tier2_hardware/thinking_centos7_hardware.rst
source/software/python_package_management.rst

* Make spelling of 'quick start' consistent.
* Fix old markdown link to `conda` information.

Minor corrections

---

source/jobs/credit_system_basics.rst
source/leuven/breniac_quickstart.rst
source/leuven/credits.rst
source/leuven/genius_quick_start.rst
source/leuven/thinking7_quickstart.rst
source/leuven/tier1_hardware/breniac_hardware.rst
source/leuven/tier1_hardware/breniac_login_nodes.rst

A link to a somewhat outdated PDF was sent to new users of Breniac.  The information therein has now been added to the documentation site, updated and streamlined.

Add quick start for Breniac

---

source/user_support.rst

The guidelines for support requests have had a small update:
* request to copy/paste terminal text rather than sending a screenshot,
* request to add the cluster name for software that malfunctions,
* slight rephrasing to make subsections wording consistent.

Support request info revision

---

source/software/links.rst
source/software/mpi_for_distributed_programming.rst

* (Temporarily) remove section on MPT.
* Update status of MPI specification support.
* Fix link to ArmForge tutorial videos.

Fixes to development documentation

---

source/leuven/breniac_quickstart.rst

An extremely tiny (but still relevant!) change, which seemed like a good occasion to start working on VscDocumentation.
So the thing is that the Breniac debug job example displayed a walltime of 2 hours, but the maximum debug queue walltime (as specified in the lines above it) is only 1 hour.

Lower job walltime to comply with debug walltime limit

---

source/security_measures_20200520.rst

- avoid confusion between SSH public/private keys & key pair (especially "`Upload a new SSH key pair` is wrong, only pubkey is uploaded)
- add emphasis by putting a couple of sentences in bold
- clarify warning w.r.t. uploading new pubkey before May 27
- add note mentioning that it takes a while before new pubkey becomes active (to avoid tickets by impatient users)

fixes & clarifications for 20 May 2020 measures 

---

source/leuven/running_jupyter_notebooks.rst

Correct a small mistake in the instructions to start the server for running Jupyter notebooks using NX.

Fix instructions for running a Jupyter notebook using NX

---

source/leuven/genius_quick_start.rst

Adds explanation of the exclusive_process, exclusive_thread, and default features that can be specified for GPUs. Probably only relevant for advanced users.

Add information on GPU compute modes

---

source/leuven/breniac_quickstart.rst

Hopefully this note will restrain users from "oversubmitting" jobs.
I do not know who decided to put different limits for each queue, it makes things more complicated than they should be.

Add note about maximal number of user jobs in BrENIAC queue

---

source/jobs/specifying_resources.rst

Mentioning cases where `qos=shared` needs to be added in order to really get the `singlejob` node access policy (see also [Redmine ticket 76617](https://scm.icts.kuleuven.be/issues/76617)). As this is a minor change (adding one sentence), I will merge it right away.

More info on singlejob policy

---

source/conf.py

this reduces the lengthy text on the navigation bar from 'VSC documentation 1.0 documentation' to simply 'VSC documentation'

add html_title

---

source/leuven/genius_quick_start.rst

A few users were accustomed to the 21-day on ThinKing, and brought up
that the Genius documentation doesn't say that 7-day is the limit.
(Also some cosmetic changes to the debugging part)

Add basic Genius walltime info

---

source/leuven/genius_quick_start.rst

There are limits on how many jobs a user can have queued simultaneously. If a limit is exceeded, jobs end up in qdef and will not start without manual intervention. This PR adds a note about which limits are in place.

Add note about maximal number of jobs in Genius queues

---

source/globus/cli.rst
source/globus/globus_main_index.rst
source/globus/links.rst

This adds a page on globus-cli and globus-timer-cli, sticking to basic information
(as the online documentation is pretty good). Anything you'd like to see added or changed?

Add page on the Globus CLI tools

---

source/gent/tier1_hortense.rst

rendered preview available at https://boegel-vsc-docs.readthedocs.io/en/hortense/gent/tier1_hortense.html#access-to-licensed-software

document how to get access to license software on Hortense

---

source/gent/tier1_hortense.rst

Preview at https://boegel-vsc-docs.readthedocs.io/en/hortense/gent/tier1_hortense.html#specifying-a-project
Note: picking up on `$SLURM_ACCOUNT` requires `jobcli` 0.6.2, which is not deployed yet on Hortense right now, but will be very soon (later today, if all goes well)

document how to specify project when submitting jobs on Hortense

---

source/gent/tier1_hortense.rst

Partially overlaps with @hajgato's PR #240, I plan to tackle the other parts in separate PRs...
Rendered preview available at https://boegel-vsc-docs.readthedocs.io/en/hortense_login/gent/tier1_hortense.html#getting-access

update section of Hortense access: list login node host keys + mention web portal

---

source/access/where_can_i_store_what_kind_of_data.rst
source/gent/tier2_hardware.rst
source/leuven/tier2_hardware/kuleuven_storage.rst

We had a few (two I believe) cases where users transferred files to $VSC_SCRATCH which were nearly immediately deleted because the access timestamp was not updated. This PR clarifies how the automatic removal works and what the implications are for initially putting files on $VSC_SCRATCH.

Explain how automatic file removal on scratch works

---

source/leuven/tier2_hardware/wice_hardware.rst
source/leuven/wice_quick_start.rst

This PR makes some small modifications to the wice documentation:
- correct come typos
- replace weird characters in job submission examples that gave rise to errors when copy-pasting
- add a note that it is possible to submit interactive jobs on partitions other than the interactive partition as well
- update the bigmem job example so it requests the maximal amount of memory (28000M per core, note that 28G will not work as slurm considers 28G=1024*28M)
- update the status to _nearly in production_

Extend wice documentation

---

source/access/ssh_config.rst

required in some cases, specifically in macOS with OpenSSH_8.6p1

move 'Match User' section to the end of the config file

---

source/data/iCommands.rst

Installation instructions were incomplete, lacking:
- the prerequisites (in case of Ubuntu 20)
- The adding of the repository

fix installation instructions

---

source/conf.py

By default, the [Docutils Smart Quotes transform](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-smartquotes) converts double dashes in a text block as a single 'en dash'. It seems safer to not do this by default in case one either forgets to escape this in some way or when escaping is not possible or convenient.
What originally made me look into this, is that it caused problems for a user who followed the instructions on
https://docs.vscentrum.be/en/latest/antwerp/SLURM_convert_from_PBS.html#pbs-qsub-command-line-options
There might be a way to just fix it for this particular page, but I think it's safer to just to always avoid creating those 'en dashes'.

Disable Smart Quotes for dashes

---

source/leuven/wice_advanced_guide.rst
source/leuven/wice_quick_start.rst

This updates the `Environment propagation` paragraph in the wICE advanced guide, now that the CLI filter is in place.

Update environment export behavior on wICE (plus Worker and Conda tips)

---

source/data/iCommands.rst

iCommands for iRODS 4.3.0 are available for most modern linux versions, opposed to 4.2.11, and have been shown to work well with irods server version 4.2.11.

Update iCommands installation instructions to 4.3

---

source/leuven/genius_quick_start.rst
source/leuven/tier2_hardware/genius_hardware.rst

Just something I noticed the other day and that would be good to fix.
(A "G" (or 'g') unit multiplies by 1024, so these two examples would not behave as expected (the first one would get rejected upon submission, the second one leads to additional cores being allocated to satisfy the memory requirement).)

Use appropriate memory per core value (Genius quickstart)

---

source/globus/access.rst

External users cannot use the VSC collections of Globus, so this needed to be added to the documentation.

add comment on exception for externals

---

source/access/index.rst
source/access/using_the_xming_x_server_to_display_graphical_programs.rst
source/access/windows_client.rst
source/conf.py
styleguide.md

A few links to the VSC website in the access section are broken (thanks to @jantur3k for catching those :beers:)  . They use URLs from a named reference and lack a `_` to get the reference interpreted as such.
This is a weird error that results in a broken link but does not triger any warning or error at compile time. That's why it went through the cracks.
I'm also updating the styleguide to cover this case.

fix links to VSC website in Access section

---

source/leuven/genius_2_rocky.rst

I have made some quite aggressive changes to the Genius to Rocky 8 page, I hope everyone is ok with that. My main objectives are:
* Provide a more extensive description of how the cluster module works
* Make sure most of this page remains valid _after_ the migration, since I think that the discussion on the cluster module should be permanent and not temporary.
I have a few remarks
* There is some overlap with other pages such as https://docs.vscentrum.be/software/software_stack.html or https://docs.vscentrum.be/gent/setting_up_the_environment_using_lmod_at_the_hpc_ugent_clusters.html# In the long term it would be good to merge it in there (although there can be some CUE issues)
* In a few other places, we recommend to execute `module use` to adapt the modulepath. This will no longer be …

Revamp the Genius to Rocky 8 page

---

source/leuven/wice_advanced_guide.rst

Added short statement in "Conda on wICE" that the interactive Slurm partition can be used for Conda environment management on wICE.

Conda on wICE management - interactive session

---

source/leuven/genius_2_rocky.rst

There was still a reference to the `lpt2_rocky8_pilot group`, which is no longer relevant. This PR removes the reference.

Remove note about Rocky8 pilot group

---

source/vsc_tutorials.rst

This PR follows #365 . I noticed that the trainings offered by other HPC sites are thoroughly documented here https://docs.vscentrum.be/interesting_links.html#training-programs-in-other-centres. However, there was no single mention of our own official VSC training page on the docs. So, this PR:
- follows that of #365 
- tries to promote VSC trainings (but a single sentence may not be enough; so, feel free to propose any improvements here)
- describes that the KUL/UH trainings are spread over various github repositories (in contrast to those of other sites which are nicely organized under a single website)
- proposed changes are only for the KUL/UH site

Extend vsc tutorials description

---

source/conf.py
source/robots.txt

Fixes (again) #366
Readthedocs generates its own `sitemap.xml` overwriting any custom one. Apparently, custom `sitemap.xml` is a paid feature.
So we will just use another filename for the sitemap. The name of the file does not really matter, crawlers will follow whatever is defined in `robots.txt`.

rename sitemap file to vsc-docs-sitemap.xml

---

source/antwerp/tier2_hardware.rst
source/antwerp/uantwerp_slurm_specifics.rst
source/antwerp/uantwerp_software_specifics.rst
source/jobs/job_advanced.rst
source/jobs/job_management.rst
source/jobs/job_submission.rst
source/jobs/job_types.rst

For this one I just
There are for sure more things that can be improved in the Slurm info pages, but so this is one piece of it ;).
Closes #385

 Collecting UA-specific Slurm info

---

source/access/generating_keys_with_putty.rst

The link for the short video doesn't exist anymore, could not find it anywhere else either.

Remove ref to video (broken link) in generating_keys_with_putty.rst

---

source/leuven/tier2_hardware/genius_hardware.rst
source/leuven/tier2_hardware/superdome_hardware.rst
source/leuven/tier2_hardware/wice_hardware.rst

This just adds the hardware details for the wICE extension, in a separate subsection.
(Once it gets opened for general usage we can put everything in the same list and update the source/leuven/tier2_hardware/wice_hardware/wice.png figure.)

Add wICE extension hardware details

---

source/cloud/terraform.md

The documentation never mentions needing to install anything except Terraform, so I added a note.

Added instructions on how to install openstack client

---

source/leuven/services/openondemand.rst

~~I suppose that `${VSC_HOME}/.local` used to be the place at some point in the past, but now at least it's necessary to use `${VSC_DATA}/.local/`, otherwise the installed kernels won't show up in the web client.~~
With these modifications the kernels will be installed in an appropriate location (searched by the Jupyter server), also when the user e.g. has set the `${XDG_DATA_HOME}` variable.

Use default user installation prefix for Jupyter kernels

---

source/jobs/specifying_resources.rst
source/jobs/submitting_and_managing_jobs_with_torque_and_moab.rst
source/jobs/why_doesn_t_my_job_start.rst

I believe none of the commands checkjob, showstart and showbf work in any of the VSC clusters

Remove information about commands checkjob, showstart and showbf 

---

source/leuven/tier2_hardware/wice_hardware.rst
source/leuven/wice_quick_start.rst

This updates the wICE hardware and quickstart pages now that we have a `gpu_a100_debug` partition.
(the diffs also again include some automatic trailing white space cleanup by my editor)

Updates w.r.t. new gpu_a100_debug partition on wICE

---

source/leuven/services/openondemand.rst
source/leuven/tier2_hardware.rst

In this PR, the OOD page is updated concerning the following items:
- new Globus button
- updates about JupyterLab and using Conda kernels
- MATLAB app
- ParaView app
Remarks:
- This PR does NOT include any update for RStudio Server; this shall happen once the issues with 'RStudio as a module' are solved.
ToDo List:
answer is: No

OOD update

---

source/how_do_i_acknowledge_the_vsc_in_publications.rst

As noted in https://github.com/hpcleuven/VscDocumentation/issues/427, the name of the virtual collection in Lirias is called "KUL-HPC" and not “High Performance Computing" (see https://research.kuleuven.be/nl/associatienet/output/lirias/faqs_webnl/overzicht-virtuele-collecties-overview-virtual-collections). It looks like this has changed during the migration to Lirias 2.0, see https://admin.kuleuven.be/icts/english/services/wms/admin/staff/migration-to-lirias-2.0.

Update Lirias virtual collection to KUL-HPC

---

source/leuven/genius_quick_start.rst
source/leuven/wice_quick_start.rst

The maximal walltime on debug partitions was increased to 1 hour.

Increase maximal walltime on KU Leuven debug partitions to 1 hour

---

source/leuven/tier2_hardware/genius_hardware.rst
source/leuven/tier2_hardware/superdome_hardware.rst
source/leuven/tier2_hardware/wice_hardware.rst

In response to a request from user(s) in the user survey of UD2023, in this PR, the information about the default memory per core is added to the following hardware specification pages. 
- genius
- superdome
- wice

Adding memory-per-core info to hardware spec pages

---

source/gent/setting_up_the_environment_using_lmod_at_the_hpc_ugent_clusters.rst
source/jobs/running_jobs_torque.rst
source/jobs/starting_programs_in_a_job.rst
source/leuven/leuven_module_system.rst
source/leuven/services/openondemand.rst
source/leuven/slurm_specifics.rst
source/leuven/tier2_genius.rst
source/leuven/wice_advanced_guide.rst
source/software/module_system_basics.rst
source/software/software_stack.rst
source/software/using_software.rst

In part to address some feedback from the last user survey, this PR proposes the following kind of changes:
(and so removing the Rocky 8 migration info, which is now quite some time behind us)
(I've based this in part on the https://github.com/hpcleuven/VscDocumentation/tree/feature/module_documentation branch, but e.g. did not include its attempt at merging the site-specific module information, which I propose to leave for a future PR ;-)
@boegel  @smoors @backelj :  just pinging you as well in case you want to chime in, since this also touches on some 'common' parts.

Refurbishing of Leuven & common module documentation pages

---

source/conf.py

I got a nice headsup from a user who mentioned that the current FileZilla download link leads to a copy that contains ads and malware. As explained [in this link](https://www.reddit.com/r/HTML/comments/1d7ko9r/is_filezilla_a_safe_program/), the current download URL leads to the quick download which is a 'sponsored version' including adware and gets detected by security as malware. For users machines equipped with malware detection, this is quite a headache. 
Instead, I replaced the download link with the direct download page from FileZilla: https://filezilla-project.org/download.php?show_all=1

Malware-free download link for FileZilla

---

source/leuven/slurm_specifics.rst

Recently, a [`job_submit.lua` plugin](https://slurm.schedmd.com/job_submit_plugins.html) got deployed on our production sites to impose a new GPU usage policy. Through the plugin, we ensure that each job requests a maximum allowed proportion of cores and memory per every requested GPU. This PR adds a new section to the [specific Slurm instructions](https://docs.vscentrum.be/leuven/slurm_specifics.html) relevant for the KU Leuven site.

KULeuven correct GPU resource proportions

---

source/leuven/services/openondemand.rst

This PR proposes few subtle typesetting improvements and typo fixes (missing space or a full-stop), only for the RStudio subsection.

typo fixes for RStudio

---

source/compute/portal/ondemand.rst

This PR updates the first paragraph of the description of RStudio, followed by the recent inclusion of R version 4.4.1 in Ondemand RStudio-Server.

allowing 2 versions of R

---

source/compute/software/matlab_getting_started.rst

When installing MATLAB using EasyBuild, it is advised not to add the paths to the MATLAB runtime libraries to LD_LIBRARY_PATH in the module file (see https://github.com/easybuilders/easybuild-easyblocks/pull/2981). But these runtime libraries are required when running comiled MATLAB code, and so LD_LIBRARY_PATH needs those paths when running compiled MATLAB code. The preferred solution is to use the wrapper script for a MATLAB executable that is generated by the MATLAB compiler when compiling MATLAB scripts (https://github.com/easybuilders/easybuild-easyblocks/issues/2965#issuecomment-1665317981). The wrapper expects a first argument that provides the rootdir of the MATLAB installation that is being used. With a MATLAB module, that rootdir is given by EasyBuild environment variable …

Document use of wrapper script for compiled MATLAB code

---

source/compute/portal/ondemand/fluent.rst
source/compute/portal/ondemand/index.rst

Fluent app will soon go to production on the KUL ondemand portal, and this PR adds a relevant page.

Adding OnDemand Fluent page
