hpcleuven/VscDocumentation

source/leuven/tier2_hardware/restoring_a_snapshot.rst
* Fix snapshot directory names.
=> Fix directory names and frequency

source/gent/tier2_hardware.rst
I checked the rendering locally, works as expected (table formatting is correct, etc.)
=> Tier2 hardware gent

source/brussels/tier2_hardware/hydra_hardware.rst
We are switching to new login nodes in Hydra on July 8th.
=> Update the hardware specs with the new login nodes of Hydra

source/access/getting_access.rst
- fixed some typos
- updated "Applying for the account" for UAntwerpen and VUB
=> update to feature/get_access

source/jobs/basic_linux_usage.rst, source/jobs/checkpointing_framework.rst, source/jobs/credit_system_basics.rst, source/jobs/how_to_get_started_with_shell_scripts.rst, source/jobs/job_submission_and_credit_reservations.rst, source/jobs/links.rst, source/jobs/monitoring_memory_and_cpu_usage_of_programs.rst, source/jobs/running_jobs.rst, source/jobs/specifying_output_files_and_notifications.rst, source/jobs/specifying_resources.rst, source/jobs/starting_programs_in_a_job.rst, source/jobs/submitting_and_managing_jobs_with_torque_and_moab.rst, source/jobs/the_job_system_what_and_why.rst, source/jobs/using_software.rst, source/jobs/what_if_jobs_fail_after_starting_successfully.rst, source/jobs/why_doesn_t_my_job_start.rst, source/jobs/worker_framework.rst
- fixed typos
- replaced :doc: by :ref:
- replaced a few non-ASCII characters
=> Minor updates

source/leuven/links.rst, source/leuven/tier2_hardware/kuleuven_storage.rst, source/leuven/using_beegfs.rst
This PR addresses issue #33 
* Add page on using BeeGFS.
* Add file with links for KU Leuven specifics.
* Add reference to BeGFS to the KU Leuven storage page.
=> Add BeeGFS page

source/faq.rst, source/what_are_standard_terms_used_in_hpc.rst
* Reformat the list into a descriptive list.
* Add GPU-related terms
=> Update list of standard terms

source/access/managing_disk_usage.rst, source/leuven/mmlsquota.rst
Based on your feedback and cross-checking with Stefan on CUE I modified the page on disk space management accordingly.
=> Modify disk space management page

source/leuven/superdome_quick_start.rst, source/leuven/tier2_hardware/superdome_hardware.rst
Try to reduce confusion in Superdome documentation.
=> Superdome documentation

source/.gitignore, source/faq.rst, source/jobs/links.rst, source/jobs/worker_framework.rst, source/jobs/worker_or_atools.rst
* Updated worker quickstart page
* Add FAQ on worker versus atools
=> worker & atools

source/.gitignore, source/leuven/tier1_hardware/breniac_hardware.rst, source/leuven/tier1_hardware/breniac_login_nodes.rst
The hardware description of Tier-1 is not on par with that of the Tier-2 infrastructure.  This PR addresses this partly by adding information on
* the login infrastructure, and
* the storage infrastructure.
=> Tier1 description update

README.md, source/leuven/running_jupyter_notebooks.rst, source/leuven/thinking7_quickstart.rst
* Add info on Tier-1 login nodes
* Add info on Tier-1 storage
=> Tier-1 description update

source/leuven/genius_quick_start.rst
Debug nodes were previously not documented.
=> Add how to use debug nodes on genius

source/access/vpn.rst, source/antwerp/tier2_hardware/hopper_hardware.rst, source/antwerp/tier2_hardware/leibniz_hardware.rst
- explicitly mention AnyConnect client
- added references to VPN page in hardware pages
=> Updated UAntwerpen VPN info

source/leuven/breniac_quickstart.rst, source/leuven/genius_quick_start.rst, source/leuven/thinking7_quickstart.rst, source/software/matlab_getting_started.rst
Corrected
- pretty crucial typo
- style.
This page requires a thorough rewrite.
=> Fix to MATLAB documentaion

source/access/access_using_mobaxterm.rst, source/access/generating_keys_with_mobaxterm.rst
MobaXterm saves keys in PuTTY format by default
=> Mobaxterm key

source/jobs/specifying_resources.rst, source/leuven/tier1_hardware/breniac_hardware.rst, source/leuven/wos_storage_quick_start_guide.rst
(just noticed there were a a few broken :ref: links)
=> A few broken :ref: links

source/leuven/genius_quick_start.rst
* Update genius node map for new debug nodes.
* Add CPU debug nodes to the quickstart.
=> Update for CPU debug nodes

source/access/generating_keys_with_openssh.rst, source/access/generating_keys_with_putty.rst, source/access/messed_up_keys.rst, source/access/nx_start_guide.rst, source/access/text_mode_access_using_openssh_or_jellyfissh.rst, source/access/upload_new_key.rst, source/access/windows_client.rst, source/antwerp/gpu_computing_uantwerp.rst, source/antwerp/licensed_software_on_the_uantwerp_clusters.rst, source/antwerp/the_foss_2017a_toolchain_and_its_subtoolchains_on_the_uantwerp_clusters.rst, source/books.rst, source/gent/tier2_hardware.rst, source/globus/data_sharing.rst, source/interesting_links.rst, source/jobs/links.rst, source/jobs/specifying_resources.rst, source/leuven/running_jupyter_notebooks.rst, source/software/foss_toolchain.rst, source/software/hybrid_mpi_openmp_programs.rst, source/software/intel_toolchain.rst, source/software/links.rst, source/software/mpi_for_distributed_programming.rst, source/software/ms_visual_studio.rst, source/software/openmp_for_shared_memory_programming.rst, source/software/parallel_software.rst, source/software/python_package_management.rst, source/software/r_package_management.rst, source/software/version_control_systems.rst, source/web_tutorials.rst
- updated several urls
- updated a few internal links
- fixed a few typos
- link to Open MPI website on page "MPI distributed programming", 4th paragraph, 1st sentence still needs to be fixed
=> Update after running "make linkcheck"

source/gent/tier2_hardware.rst
=> Add new cluster in hardware specs UGent

source/leuven/running_jupyter_notebooks.rst
Update Jupyter notebook how-to.
=> Update Jupyter notebook how-to.

source/software/python_package_management.rst, source/software/r_package_management.rst
add note to usage of `conda` for installing additional R and Python packages
=> add note to conda usage for installing additional packages

source/globus/access.rst, source/globus/links.rst, source/globus/managing_and_transferring_files.rst
@ingridbr A small change with regards to Globus
(originated from a user that tried to follow the steps
but ended up with the Console instead of the regular
interface)
=> Clarification w.r.t. Globus login / Management Console

.vscode/settings.json, source/.gitignore, source/data/user_access.rst
Hi Ingrid,
Could you please also review this change and merge it to data_M to be rendered? Thanks.
=> Added 'irods-setup' command usage

source/access/getting_access.rst, source/brussels/tier2_hardware/hydra_hardware.rst, source/jobs/specifying_resources.rst, source/user_support_addresses.rst
We got a new website and some links in VSC docs have to be updated.
I'm PRing this into `development`, if it should target another branch let me know.
=> update links to new VUB-HPC website

source/access/access_and_data_transfer.rst, source/gent/tier1_hortense.rst
rendered preview available at https://boegel-vsc-docs.readthedocs.io/en/hortense/gent/tier1_hortense.html
=> Hortense: flesh out sections on getting access + resource manager, add some details to hardware overview

source/gent/tier1_hortense.rst
preview at https://boegel-vsc-docs.readthedocs.io/en/hortense/gent/tier1_hortense.html#managing-project-members
=> add subsections on project management for Tier-1 Hortense

source/gent/tier1_hortense.rst
Added pointer to $VSC_SCRATCH_PROJECTS_BASE
=> Adjust Tier1 Hortense documentation

source/jobs/submitting_and_managing_jobs_with_torque_and_moab.rst
Some update/clarification of this paragraph, following a user ticket indicating that this needed to be improved.
=> Improve showq description

source/gent/tier1_hortense.rst
Stated how users should request GPU resources
=> Adjusted documentation with GPU info

source/leuven/wice_advanced_guide.rst, source/software/software_development.rst
Guide that provides more in-depth information on wICE, compared to the quickstart guide.
=> Add advanced guide for wICE

source/leuven/genius_quick_start.rst
=> Fix typo in Genius quick start guide

source/impact_on_research_industry_and_society.rst
I propose a small wording correction in this page. 
But beside that, I have a more general comment.
The text is trying to convince us that we need "powerful supercomputers" to advance science. But, having such machines is not enough, without having efficient code and proficient users!
So, I propose to iron out this page again, and at least use "supercomputing" instead of "supercomputer" wherever it fits into the text.
Because this specific page is a bit philosophical (!), I am not gonna propose text, as it can trigger long discussions.
=> slight wording correction is proposed

source/leuven/services/openondemand.rst
This is the second attempt at re-applying #335.
@jooghe  I broke your PR #344 trying to get these commits into it. So I had to make a new one.
=> Update feature/ondemand kul

source/leuven/genius_2_rocky.rst, source/leuven/tier2_genius.rst
Can you check the additional info regarding cluster modules and merge?
=> Genius2rocky

source/leuven/wice_advanced_guide.rst
A quick follow up after merging https://github.com/hpcleuven/VscDocumentation/pull/355.
=> Wice adv guide

requirements.txt, source/conf.py, source/robots.txt
=> Add complete sitemap

source/software/module_system.rst
This PR gives small suggestions before a PR is placed based on the `feature/module_documentation` branch.
=> WIP: Feature/module documentation before pr

source/data/transfer/network_drives/kuleuven.rst
The migration to Rocky8 also involved an update of Thunar, with changes to its user interface.
(There's also another file manager (Files/Nautilus) where the procedure is quite similar. But to keep it simple this just focuses on the default file manager.)
=> Update KU Leuven network drive GUI instructions

source/access/mfa_guide.rst, source/access/nx_start_guide.rst
I added and updated some notes on MFA and connecting via NX
=> More tips on MFA with e.g. NX

source/leuven/slurm_specifics.rst, source/leuven/tier2_hardware/genius_hardware.rst, source/leuven/tier2_hardware/wice_hardware.rst, source/leuven/wice_advanced_guide.rst, source/leuven/wice_quick_start.rst
This adds the new partitions to the quickstart (with some additional refinements) and expands the `Compiling software` part of the wICE advanced guide (i.e. what we recommend to users for these new partitions).
(There are of course a few other improvements one can think of. We might need to revise the `Conda on wICE` part, for example. But if you don't mind I would suggest to keep such things for a future PR.)
=> wICE quickstart & software installation update (wICE extension)

source/cloud/terraform.md, source/cloud/windows.md
Docs to accommodate changes in https://github.com/hpcugent/openstack-templates/pull/11
=> Update cloud terraform docs for modular modules

source/cloud/terraform.md
https://github.com/hpcugent/openstack-templates/pull/13
=> Terraform: add secgroup and volume improvements

source/software/git.rst
An attentive user found a small typo, this PR corrects it.
=> Correct typo in page about git

source/cloud/terraform.md
Add note about feature added in: https://github.com/hpcugent/openstack-templates/pull/20
=> Cloud/terraform: add port forwarding

source/cloud/configure_instances.md, source/cloud/manage_volumes.md, source/cloud/shares.md, source/cloud/terraform.md, source/cloud/windows.md
Updated docs for https://github.com/hpcugent/openstack-templates/pull/21
Requires user communication
=> Cloud: Auto-apply variables docs

source/cloud/terraform.md
Add a small tip on how to edit files on the login node
=> Terraform file tip

source/cloud/terraform.md
Adds variables introduced in https://github.com/hpcugent/openstack-templates/pull/25
=> Cloud terraform: add more variables, improve consistency.

source/cloud/terraform.md
Related to https://github.com/hpcugent/openstack-templates/pull/28
=> tf: Add small note on how to override external port

source/accounts/vsc_user_groups.rst
Afaik there is no confirmation email being sent and no further action is needed to create a new group
=> Remove confirmation email step + add waiting time

source/compute/software/r_package_management.rst
(see https://github.com/hpcleuven/VscDocumentation/pull/482#pullrequestreview-2966888884)
=> [feature/vsc-Rproject] Make the different R install parts more coherent

source/compute/portal/ondemand/interactive-apps.rst, source/compute/portal/ondemand/jupyterlab.rst, source/compute/portal/ondemand/rstudio-server.rst
- how to request more memory
- update modules loaded by default
- minor writing style changes
=> update OOD docs for VUB
